# PCN exclusions from the national staffing funnel — one place that says
# which PCNs (or which of their practices) are left out, and why.
# Two kinds:
#   - rule-based, derived from the data each build: PCNs with no PCN
#     Workforce (ARRS) return
#   - manual, listed below with the evidence for each — a PCN whose
#     return is present but implausible enough that comparing it would
#     mislead. Add one only with evidence checked against the source file,
#     never because a PCN is simply an outlier: being an outlier is what
#     the funnel is for.
# The combined list is written to docs/pcn_exclusions.md by
# write_pcn_exclusions_md() so it's reviewable without running R.

manual_pcn_exclusions <- tibble::tribble(
  ~PCN_CODE, ~reason,
  "U85476", paste(
    "PCN Workforce return looks like a whole-organisation return, not one PCN's:",
    "25.9 FTE of Clinical Directors (next-highest PCN nationally: 2.3) and",
    "54% of its 274 FTE in admin/director roles (national share: 10%) —",
    "June 2026 snapshot, checked against the individual-level file."
  )
)

# Every excluded PCN, with its reason. Practices with no GP/DPC FTE
# return used to be listed here too, but the funnel counts ARRS staff
# only, so a missing practice return no longer affects any comparison.
pcn_exclusion_list <- function(pcn_workforce, pcn_list_size) {
  labels <- dplyr::select(pcn_list_size, PCN_CODE, PCN_NAME, ICB_NAME)

  no_arrs <- pcn_workforce |>
    dplyr::filter(is.na(arrs_fte)) |>
    dplyr::transmute(
      PCN_CODE, scope = "Whole PCN",
      reason = "No rows in the PCN Workforce (ARRS) return — can't tell zero ARRS staff from a missing submission."
    )

  no_arrs_roles <- pcn_workforce |>
    dplyr::filter(arrs_fte == 0) |>
    dplyr::transmute(
      PCN_CODE, scope = "Whole PCN",
      reason = "PCN Workforce return lists no ARRS-eligible roles (only a Clinical Director and/or admin) — reads as ARRS staff recorded elsewhere, not none."
    )

  manual <- dplyr::mutate(manual_pcn_exclusions, scope = "Whole PCN")

  dplyr::bind_rows(no_arrs, no_arrs_roles, manual) |>
    dplyr::inner_join(labels, by = "PCN_CODE") |>
    dplyr::select(PCN_CODE, PCN_NAME, ICB_NAME, scope, reason) |>
    dplyr::arrange(PCN_NAME)
}

write_pcn_exclusions_md <- function(pcn_exclusions, path = "docs/pcn_exclusions.md") {
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  md_table <- function(df) {
    c("| PCN code | PCN | ICB | Reason |", "|---|---|---|---|",
      sprintf("| %s | %s | %s | %s |", df$PCN_CODE, df$PCN_NAME, df$ICB_NAME, df$reason))
  }

  writeLines(c(
    "# PCN exclusions from the staffing funnel",
    "",
    "Generated by `write_pcn_exclusions_md()` in `src/pcn_exclusions.R` on every",
    "`targets::tar_make()` — do not edit by hand. Rule-based exclusions come from",
    "the data; manual ones are listed, with evidence, in `manual_pcn_exclusions`.",
    "",
    sprintf("## PCNs left out (%d)", nrow(pcn_exclusions)),
    "",
    md_table(pcn_exclusions)
  ), path)
  path
}
